# Generated by Django 4.2.1 on 2023-05-28 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Coords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.IntegerField()),
                ("logitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("image", models.BinaryField(editable=True)),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winter", models.CharField(max_length=4)),
                ("spring", models.CharField(max_length=4)),
                ("summer", models.CharField(max_length=4)),
                ("autumn", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="PerevalAdded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beauty_title", models.CharField(default="пер.", max_length=64)),
                ("title", models.CharField(default="Название", max_length=64)),
                (
                    "other_titles",
                    models.CharField(default="Другие названия", max_length=128),
                ),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest.customuser",
                    ),
                ),
                (
                    "connect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rest.connect"
                    ),
                ),
                (
                    "coords",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rest.coords"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="PerevalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rest.image"
                    ),
                ),
                (
                    "pereval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest.perevaladded",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="images",
            field=models.ManyToManyField(through="rest.PerevalImage", to="rest.image"),
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest.level"
            ),
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="status",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="rest.status"
            ),
        ),
    ]
