# Generated by Django 4.2.1 on 2023-05-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.IntegerField(default=9999999999),
        ),
    ]
