# Generated by Django 4.2.1 on 2023-05-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0002_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perevaladded",
            name="connect",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rest.connect",
            ),
        ),
    ]
