# Generated by Django 4.2.1 on 2023-05-28 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0003_alter_perevaladded_connect"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perevaladded",
            old_name="author",
            new_name="user",
        ),
    ]
