# Generated by Django 4.2.1 on 2023-05-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0004_rename_author_perevaladded_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otc",
            field=models.CharField(default="Отчество", max_length=64),
        ),
    ]
