# Generated by Django 4.2.1 on 2023-05-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0010_alter_customuser_options_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="autumn",
            field=models.CharField(default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="level",
            name="spring",
            field=models.CharField(default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="level",
            name="summer",
            field=models.CharField(default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="level",
            name="winter",
            field=models.CharField(default="", max_length=4),
        ),
    ]
