# Generated by Django 4.2.1 on 2023-05-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_alter_perevaladded_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevaladded',
            name='connect',
        ),
        migrations.DeleteModel(
            name='Connect',
        ),
    ]
