# Generated by Django 4.2.1 on 2023-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_remove_perevaladded_connect_delete_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevaladded',
            name='connect',
            field=models.CharField(null=True),
        ),
    ]
