# Generated by Django 4.2.1 on 2023-05-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
